<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<LangVersion>preview</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BepInEx.Analyzers" Version="1.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="BepInEx.Core" Version="5.4.21" />

		<PackageReference Include="R2API" Version="5.0.5" />

		<PackageReference Include="R2API.Core" Version="5.3.0" />
		<PackageReference Include="R2API.Language" Version="1.1.0" />
		<PackageReference Include="R2API.Prefab" Version="1.1.1" />
		<PackageReference Include="Rune580.Mods.RiskOfRain2.RiskOfOptions" Version="2.8.5" />

		<PackageReference Include="UnityEngine.Modules" Version="6000.3.7" IncludeAssets="compile" />
		<PackageReference Include="MMHOOK.RoR2" Version="2025.12.9" NoWarn="NU1701" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="AllyNames">
	    <HintPath>..\lib\AllyNames-nstrip.dll</HintPath>
	  </Reference>
	  <Reference Include="CoolerEclipse">
	    <HintPath>..\lib\CoolerEclipse-nstrip.dll</HintPath>
	  </Reference>
	  <Reference Include="DebuggingPlains">
	    <HintPath>..\lib\DebuggingPlains-nstrip.dll</HintPath>
	  </Reference>
	  <Reference Include="GoldenCoastPlusRevived">
	    <HintPath>..\lib\GoldenCoastPlusRevived-nstrip.dll</HintPath>
	  </Reference>
	  <Reference Include="Inferno">
	    <HintPath>..\lib\Inferno-nstrip.dll</HintPath>
	  </Reference>
	  <Reference Include="LittleGameplayTweaks">
	    <HintPath>..\lib\LittleGameplayTweaks-nstrip.dll</HintPath>
	  </Reference>
	  <Reference Include="MysticsRisky2Utils">
	    <HintPath>..\lib\MysticsRisky2Utils-nstrip.dll</HintPath>
	  </Reference>
	  <Reference Include="Nautilus">
	    <HintPath>..\lib\lib\Nautilus-nstrip.dll</HintPath>
	  </Reference>
	  <Reference Include="PhotoMode">
	    <HintPath>..\lib\PhotoMode-nstrip.dll</HintPath>
	  </Reference>
	  <Reference Include="ShaderSwapper">
	    <HintPath>..\lib\ShaderSwapper.dll</HintPath>
	  </Reference>
	  <Reference Include="SkillsmasPlugin">
	    <HintPath>..\lib\SkillsmasPlugin-nstrip.dll</HintPath>
	  </Reference>
	  <Reference Include="Starstorm2">
	    <HintPath>..\lib\Starstorm2-nstrip.dll</HintPath>
	  </Reference>
	  <Reference Include="Unity.Postprocessing.Runtime">
	    <HintPath>..\lib\Unity.Postprocessing.Runtime.dll</HintPath>
	  </Reference>
	  <Reference Include="UnityHotReload">
	    <HintPath>..\lib\UnityHotReload.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="content\" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec Command="$(SolutionDir)butterscotchnroses/postbuild.sh $(SolutionDir) $(ConfigurationName)"/>
	</Target>
</Project>